[package]
name = "app_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
strum = { workspace = true }
dotenvy = { workspace = true }